#!/usr/bin/env -S uv run --quiet --script
# /// script
# requires-python = ">=3.10"
# dependencies = ["requests"]
# ///
"""
Drive a real conversation with a LEAI survey's AI agent without opening a
browser, and persist every turn to the FeedbackMessage table so the result
shows up in the FeedbackAnalyzer.

The bot turns are generated by Claude Code in headless mode (`claude -p`)
using the survey's `instructions` field as the session's system prompt —
NOT by the live `/openai-chat/` proxy. This lets us iterate on prompt
design without burning OpenAI calls and without opening a browser.

Usage
-----
    LEAI/scripts/simulate_conversation.py \
        --public-id jDl3ywdzr1uf \
        --turns LEAI/scripts/personas/maya.json

    # Local Django backend instead of Heroku
    LEAI/scripts/simulate_conversation.py \
        --public-id jDl3ywdzr1uf \
        --turns LEAI/scripts/personas/maya.json \
        --api http://localhost:8000/datapipeline/api

Persona JSON format
-------------------
    {
        "name": "Maya",
        "notes": "engaged grad student, anxious about rigor",
        "turns": [
            "first scripted student message...",
            "second scripted student message...",
            ...
        ]
    }
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
import uuid
from pathlib import Path
from typing import Optional

import requests

# Form-mapping mode mirror — see LEAI/docs/instructor-clarifications/wk6-form-mode-SPEC.md §6.
sys.path.insert(0, str(Path(__file__).resolve().parent))
import leai_formmode as fm  # noqa: E402

API_PROD = "https://guiidata-b6c968e6ed85.herokuapp.com/datapipeline/api"
API_LOCAL = "http://localhost:8000/datapipeline/api"

# Mirrors `withOneQuestionGuardrail` in feedback.html so the bot we drive
# here is given the same constraints as the live one.
ONE_QUESTION_GUARDRAIL = """

ONE-QUESTION GUARDRAIL (highest priority, overrides anything above):
- Ask AT MOST one question per turn. Zero questions is also acceptable (for example, a brief acknowledgement like "Thanks, got it." when there is nothing more to probe or when wrapping up).
- Never bundle multiple questions into a single reply. Do NOT produce numbered or bulleted lists of questions, do NOT chain questions with "and" / "also" / "as well as", and never include more than one "?" character in a message.
- If several topics are relevant, pick the single most relevant one for this turn and save the others for later turns once the student has answered.
- This rule applies to every turn including the opening message and the concluding bot-feedback message.
"""

# Mirrors `generateIntroductoryMessage` in feedback.html — the kickoff message
# that asks the model to greet the student and pose the first question.
INTRO_USER_MSG = "Begin the conversation. Greet the student briefly and ask your first question."

# Tools we forbid Claude from invoking. The survey is a pure roleplay; the
# bot has no business reading the filesystem or running shell commands.
DISALLOWED_TOOLS = (
    "Bash,Read,Write,Edit,Glob,Grep,WebFetch,WebSearch,TodoWrite,Task,Agent,"
    "NotebookEdit,LS,SlashCommand"
)


# ─── survey config ────────────────────────────────────────────────────────

def fetch_survey(api: str, public_id: str, team_number: int | None = None) -> dict:
    r = requests.get(
        f"{api}/get_feedback_gpt_by_public_id/",
        params={"public_id": public_id},
        timeout=20,
    )
    r.raise_for_status()
    gpt = r.json()
    if not gpt.get("is_active", False):
        sys.exit(f"survey {public_id} is not active (reason={gpt.get('reason')!r})")
    if gpt.get("mode") == "group":
        # In-group surveys are bound to a SurveyTeamSnapshot. Default to the
        # first team under the snapshot; --team <number> selects a specific one
        # so several personas can be spread across studios in one run. The pick
        # is persisted via assign_session_to_team in run() once session_id exists.
        snap_resp = requests.get(
            f"{api}/survey_team_snapshot/",
            params={"public_id": public_id}, timeout=20,
        )
        if snap_resp.status_code != 200:
            sys.exit(f"in-group survey {public_id} has no team_snapshot ({snap_resp.status_code})")
        snap = snap_resp.json()
        teams = snap.get("teams") or []
        if not teams:
            sys.exit(f"in-group survey {public_id} has a snapshot but no teams under it")
        if team_number is None:
            team = teams[0]
        else:
            matches = [t for t in teams if t.get("number") == team_number]
            if not matches:
                avail = ", ".join(str(t.get("number")) for t in teams)
                sys.exit(f"--team {team_number} not found under {public_id}; available: {avail}")
            team = matches[0]
        gpt["_team_id"] = team["id"]
        gpt["_team_label"] = team.get("display_name") or f"{snap.get('label_prefix','Team')} {team.get('number')}"
    return gpt


# ─── claude code wrapper ──────────────────────────────────────────────────

def claude_turn(
    user_text: str,
    *,
    system_prompt: Optional[str],
    session_id: Optional[str],
    timeout: int,
) -> tuple[str, str]:
    """Run one turn through `claude -p`. Returns (response_text, session_id)."""
    # Note: we deliberately do NOT pass `--bare`. `--bare` disables OAuth /
    # keychain auth, which would force every user to set ANTHROPIC_API_KEY.
    # `--system-prompt` already fully replaces the default system prompt,
    # so CLAUDE.md, env info, and built-in tool instructions are excluded
    # from the bot's context anyway — `--bare` would add nothing here.
    cmd = [
        "claude", "-p",
        "--output-format", "json",
        "--disallowed-tools", DISALLOWED_TOOLS,
    ]
    if session_id:
        cmd += ["--resume", session_id]
    if system_prompt is not None:
        cmd += ["--system-prompt", system_prompt]

    proc = subprocess.run(
        cmd, input=user_text, capture_output=True, text=True, timeout=timeout
    )
    if proc.returncode != 0:
        sys.exit(
            f"claude -p failed (rc={proc.returncode}):\n"
            f"  stderr: {proc.stderr.strip()}\n"
            f"  stdout: {proc.stdout.strip()[:500]}"
        )

    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError:
        sys.exit(f"claude -p did not return JSON:\n{proc.stdout[:500]}")

    text = (data.get("result") or "").strip()
    sid = data.get("session_id") or session_id
    if not text:
        sys.exit(f"claude -p returned an empty result. raw: {data}")
    if not sid:
        sys.exit(f"claude -p did not return a session_id. raw: {data}")
    return text, sid


# ─── feedback persistence ─────────────────────────────────────────────────

def persist_message(
    api: str,
    *,
    gpt: dict,
    session_id: str,
    role: str,            # 'ai-message' | 'user-message'
    text: str,
    seq: int,
    research_consent: bool,
    referred: bool = False,
) -> None:
    payload = {
        "session_id": session_id,
        "student_id": session_id,
        "sent_by": role,
        "content": text,
        "gpt_used": gpt["name"],
        "gpt_id": gpt["id"],
        "research_consent": research_consent,
        # True on the AI turn that fired the POINT TO A HUMAN nudge, so a
        # simulated distressed persona produces a Nudged chip in the analyzer.
        "referred": referred,
        "client_seq": seq,
        "client_ts": int(time.time() * 1000) + seq,
    }
    r = requests.post(f"{api}/feedback_message_api/", json=payload, timeout=20)
    if r.status_code >= 300:
        sys.exit(f"persist failed (HTTP {r.status_code}): {r.text[:300]}")


# ─── main loop ────────────────────────────────────────────────────────────

def run(args: argparse.Namespace) -> int:
    api = args.api.rstrip("/")
    persona = json.loads(Path(args.turns).read_text())
    name = persona.get("name", "anon")
    student_turns = persona["turns"]
    if not student_turns:
        sys.exit("persona has no turns")

    print(f"→ fetching survey {args.public_id} from {api}")
    gpt = fetch_survey(api, args.public_id, args.team)
    print(f"  survey: {gpt['name']!r}  id={gpt['id']}  week={gpt.get('week_number')}")

    # Form-mapping mode activates when --form is passed. Engine state lives
    # alongside the conversation; per-turn directives are prepended to the
    # student message so the LLM sees them as engine instructions for THIS turn.
    fm_state = None
    base_system_prompt = (gpt.get("instructions") or "") + ONE_QUESTION_GUARDRAIL
    if args.form:
        schema = fm.load_schema(args.form)
        # POINT TO A HUMAN is a Course-level setting served on the gpt payload,
        # not part of the FormSchema body. feedback.html overlays it onto the
        # schema before handing it to the engine (see its activateFormMode);
        # mirror that here or the 7th gate stays disarmed and every simulated
        # conversation misrepresents production for referral-enabled courses.
        if gpt.get("referral_enabled"):
            schema = {**schema,
                      "referral_enabled": True,
                      "referral_text": gpt.get("referral_text") or ""}
        fm_state = fm.init_engine(schema)
        base_system_prompt = base_system_prompt + fm.system_prompt_tail(schema)
        referral_note = " referral:on" if schema.get("referral_enabled") else ""
        print(f"  form-mode: {schema['schema_id']}  ({len(schema['sections'])} areas){referral_note}")

    system_prompt = base_system_prompt
    survey_session = str(uuid.uuid4())  # the LEAI-side anonymous session id
    claude_session: Optional[str] = None
    seq = 0

    print(f"\n[{name}]  survey_session={survey_session}")
    if gpt.get("_team_id"):
        assign_resp = requests.post(
            f"{api}/session_team_assignment/",
            json={"session_id": survey_session, "survey_team_id": gpt["_team_id"]},
            timeout=20,
        )
        if assign_resp.status_code >= 300:
            sys.exit(f"team-assign failed (HTTP {assign_resp.status_code}): {assign_resp.text[:200]}")
        print(f"[{name}]  bound to team {gpt['_team_id']} ({gpt['_team_label']!r})")
    print(f"[{name}]  spawning Claude Code session as Remi…")

    # Opening turn. In form-mode the engine builds the directive for the opening.
    intro_user_msg = INTRO_USER_MSG
    if fm_state is not None:
        pre = fm.before_turn(fm_state, None)
        if pre.directive:
            intro_user_msg = pre.directive["text"] + "\n\n" + INTRO_USER_MSG

    raw_intro, claude_session = claude_turn(
        intro_user_msg,
        system_prompt=system_prompt,
        session_id=None,
        timeout=args.timeout,
    )
    intro_referred = False
    if fm_state is not None:
        post = fm.after_turn(fm_state, raw_intro)
        intro = post.displayed_message
        intro_referred = post.referred
    else:
        intro = raw_intro

    seq += 1
    persist_message(
        api, gpt=gpt, session_id=survey_session,
        role="ai-message", text=intro, seq=seq,
        research_consent=args.research_consent,
        referred=intro_referred,
    )
    print(f"  [{seq:02d}] BOT: {_preview(intro)}")
    if fm_state is not None:
        print(f"        ↳ engine: {fm.progress_label(fm_state)}")

    # Each scripted student turn → bot reply.
    ended = False
    for student in student_turns:
        if ended:
            break

        seq += 1
        persist_message(
            api, gpt=gpt, session_id=survey_session,
            role="user-message", text=student, seq=seq,
            research_consent=args.research_consent,
        )
        print(f"  [{seq:02d}] STU: {_preview(student)}")

        if fm_state is not None:
            pre = fm.before_turn(fm_state, student)
            if pre.short_circuit:
                # Engine handles the response (STOP intercept). Do not call LLM.
                display = pre.synthetic_response
                ended = pre.ended
                seq += 1
                persist_message(
                    api, gpt=gpt, session_id=survey_session,
                    role="ai-message", text=display, seq=seq,
                    research_consent=args.research_consent,
                )
                tail = "  ⟵ [END]" if ended else "  ⟵ [engine STOP intercept]"
                print(f"  [{seq:02d}] BOT: {_preview(display)}{tail}")
                if not ended:
                    continue
                else:
                    break
            # Prepend engine's per-turn directive so the LLM sees both.
            framed = (pre.directive["text"] + "\n\n[STUDENT MESSAGE]\n" + student) if pre.directive else student
        else:
            framed = student

        raw_reply, claude_session = claude_turn(
            framed,
            system_prompt=None,
            session_id=claude_session,
            timeout=args.timeout,
        )

        referred = False
        if fm_state is not None:
            post = fm.after_turn(fm_state, raw_reply)
            display = post.displayed_message
            ended = post.ended
            referred = post.referred
        else:
            ended = "[END]" in raw_reply
            display = raw_reply.replace("[END]", "").strip()

        seq += 1
        persist_message(
            api, gpt=gpt, session_id=survey_session,
            role="ai-message", text=display, seq=seq,
            research_consent=args.research_consent,
            referred=referred,
        )
        tail = "  ⟵ [END]" if ended else ""
        print(f"  [{seq:02d}] BOT: {_preview(display)}{tail}")
        if fm_state is not None and not ended:
            print(f"        ↳ engine: {fm.progress_label(fm_state)}")

    print(
        f"\n✓ done. turns={seq}  "
        f"survey_session={survey_session}  "
        f"claude_session={claude_session}  "
        f"ended_by_END={ended}"
    )
    if fm_state is not None:
        covered = sum(1 for s in fm_state.schema["sections"]
                      if fm_state.coverage[s["id"]].response_received)
        print(f"  form-mode coverage: {covered} / {len(fm_state.schema['sections'])} areas")
    return 0


def _preview(s: str, n: int = 110) -> str:
    s = s.replace("\n", " ")
    return s if len(s) <= n else s[:n] + "…"


# ─── cli ──────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--public-id", required=True,
                   help="Survey public_id (e.g. jDl3ywdzr1uf)")
    p.add_argument("--turns", required=True,
                   help="Path to persona JSON ({name, notes, turns:[...]})")
    p.add_argument("--api", default=API_PROD,
                   help=f"API base URL. Default: {API_PROD}.  "
                        f"For local Django: {API_LOCAL}")
    p.add_argument("--research-consent", default="true",
                   choices=["true", "false"],
                   help="Value of the persisted research_consent flag (default: true)")
    p.add_argument("--timeout", type=int, default=180,
                   help="Per-turn timeout for `claude -p` in seconds (default: 180)")
    p.add_argument("--form", default=None,
                   help="Form-mode schema id (e.g. hci271-week6-reflection). "
                        "Activates the engine mirror that wraps every turn.")
    p.add_argument("--team", type=int, default=None,
                   help="In-group surveys only: bind this session to the team with "
                        "this number under the survey's snapshot (default: first team). "
                        "Lets one run spread personas across several teams.")
    args = p.parse_args()
    args.research_consent = args.research_consent == "true"
    return args


if __name__ == "__main__":
    sys.exit(run(parse_args()))
